### ISSUE TITLE
Adapt master DS script to real DS

### ISSUE THREAD

**Issue by katrina-cityofdetroit** [kwheelan/COD-budget-helper-scripts#6]
## Goal

Fix script to work with actual returned detail sheets in Analyst Review folder

## Tasks
 - [ ] Edit template as needed (add object codes for salary/wages to Fringe Rate tab)
 - [x] Fix missing formula columns
 - [x] Adjust code to create summary tab
 - [x] Inspect DS files for unexpected data
 - [x] Test DS files one by one
 - [x] Send draft to Noah to check over
 - [ ] Reorganize code into discrete files and into classes
 - [ ] Parallelize and/or optimize write/read so it's not so slow

#### Check for: 
- No red check boxes on summary tab
- No doubled appropriations in table
- No errors or missing formulas in tabs
- Spelling errors in initiatives
- no external links

| Department | Issues with original Excel? | Tested with script? | Notes |
| -------- | ------- | ------- | ----- |
| 10 - Airport | Some appropriations have an apostrophe before the numbers, but it doesn't seem to have affected anything. |  Yes | DS has been edited; need to download new copy |
| 13 - BSEED| All good|  Yes | |
| 16 - CDD | All good|  Yes | | 
| 18 - DSLP| Appropriations missing for last few lines in NP tab (explains issue in check for appropriations table); The expenses table for Fixed Charges  |  Yes | |
| 19 -DPW | Check fails because it didn't count "Baseline Capital" as Baseline. Edit SUMIFS to use "Baseline*" instead of "Baseline" |  | |
| DDOT | Fixed missing approp code in table | | |
| DDOT - Mobility Innovation | Expenses by category was missing operating services -- now fixed | | |
| 23 - OCFO: Demolition |  |  Yes | |
| 36 - HRD Classic | Awaiting new approp code for NP line 349 (housing counseling services); some strange revenue stuff:  department used negative supplemental lines to adjust revenue estimates; should the sale of assets & compensation for losses (lines 21-23) be one-time instead of recurring? To be consistent, lines 26-27 should be 26 = $2.8 M and 27 = -$650,000; Most of the supplemental FTE requests say "transfer from ARPA" but are also marked as vacant -- maybe a mistake? | | |
| 50 - OAG | FTE tab named incorrectly | | |
| DoIT | Has 2 copies; confusing | | |
| HRD JET | 2 Versions | | |
| DWSD | Empty |||
| Library | Not named analyst review file | | |
| 54 - OIG | Job code 011712 added to just the Gold Book for OIG | | |
